export const queryKeys = {
  notifications: {
    all: ['notifications'],
    list: (category, limit) => [...queryKeys.notifications.all, 'list', category, limit],
    unread: () => [...queryKeys.notifications.all, 'unread'],
    unreadByCategory: () => [...queryKeys.notifications.all, 'unreadByCategory'],
  },
  profile: {
    all: ['profile'],
    detail: (userId) => [...queryKeys.profile.all, 'detail', userId],
    byUsername: (username) => [...queryKeys.profile.all, 'username', username],
    activity: (userId, limit) => [...queryKeys.profile.all, 'activity', userId, limit],
    achievements: (userId) => [...queryKeys.profile.all, 'achievements', userId],
    badges: (userId) => [...queryKeys.profile.all, 'badges', userId],
  },
  follow: {
    all: ['follow'],
    status: (userId) => [...queryKeys.follow.all, 'status', userId],
  },
  communities: {
    all: ['communities'],
    list: (sort, search, category) => [...queryKeys.communities.all, 'list', sort, search, category],
    detail: (id) => [...queryKeys.communities.all, 'detail', id],
    members: (id) => [...queryKeys.communities.all, 'members', id],
    messages: (id, q) => [...queryKeys.communities.all, 'messages', id, q],
    announcements: (id) => [...queryKeys.communities.all, 'announcements', id],
    pins: (id) => [...queryKeys.communities.all, 'pins', id],
    competitions: (id) => [...queryKeys.communities.all, 'competitions', id],
    rules: (id) => [...queryKeys.communities.all, 'rules', id],
    settings: (id) => [...queryKeys.communities.all, 'settings', id],
    joinRequests: (id) => [...queryKeys.communities.all, 'joinRequests', id],
    bans: (id) => [...queryKeys.communities.all, 'bans', id],
    mutes: (id) => [...queryKeys.communities.all, 'mutes', id],
    modDashboard: (id) => [...queryKeys.communities.all, 'modDashboard', id],
    rooms: (id) => [...queryKeys.communities.all, 'rooms', id],
    roomTimer: (id, roomId) => [...queryKeys.communities.all, 'roomTimer', id, roomId],
    roomTimeline: (id, roomId, date) => [...queryKeys.communities.all, 'roomTimeline', id, roomId, date],
    roomStats: (id, roomId) => [...queryKeys.communities.all, 'roomStats', id, roomId],
    heatmap: (id, year) => [...queryKeys.communities.all, 'heatmap', id, year],
  },
  leaderboard: {
    all: ['leaderboard'],
    global: (metric, limit) => [...queryKeys.leaderboard.all, 'global', metric, limit],
    communityMonthly: (id, year, month, filter) => [...queryKeys.leaderboard.all, 'communityMonthly', id, year, month, filter],
    communityAllTime: (id) => [...queryKeys.leaderboard.all, 'communityAllTime', id],
    position: (id) => [...queryKeys.leaderboard.all, 'position', id],
    usersMonthly: (year, month, limit) => [...queryKeys.leaderboard.all, 'usersMonthly', year, month, limit],
    communitiesMonthly: (year, month, category, limit) => [...queryKeys.leaderboard.all, 'communitiesMonthly', year, month, category, limit],
    stats: (year, month) => [...queryKeys.leaderboard.all, 'stats', year, month],
    search: (q, year, month, type) => [...queryKeys.leaderboard.all, 'search', q, year, month, type],
    hallOfFame: (communityId) => [...queryKeys.leaderboard.all, 'hallOfFame', communityId],
  },
  communityPanel: {
    full: (id) => ['communityPanel', 'full', id],
    heatmap: (id, year) => ['communityPanel', 'heatmap', id, year],
  },
  invitations: {
    all: ['invitations'],
    list: () => [...queryKeys.invitations.all, 'list'],
  },
  competitions: {
    all: ['competitions'],
    leaderboard: (id) => [...queryKeys.competitions.all, 'leaderboard', id],
  },
  people: {
    all: ['people'],
    suggested: (limit) => [...queryKeys.people.all, 'suggested', limit],
    search: (q) => [...queryKeys.people.all, 'search', q],
  },
  dm: {
    all: ['dm'],
    conversations: () => [...queryKeys.dm.all, 'conversations'],
    unread: () => [...queryKeys.dm.all, 'unread'],
    messages: (convId, limit) => [...queryKeys.dm.all, 'messages', convId, limit],
  },
  flashcards: {
    all: ['flashcards'],
    list: () => [...queryKeys.flashcards.all, 'list'],
    decks: () => [...queryKeys.flashcards.all, 'decks'],
    forDeck: (deckId) => [...queryKeys.flashcards.all, 'forDeck', deckId],
    dueCount: () => [...queryKeys.flashcards.all, 'dueCount'],
  },
  goals: {
    all: ['goals'],
    list: (userId) => [...queryKeys.goals.all, 'list', userId],
    data: (userId) => [...queryKeys.goals.all, 'data', userId],
  },
  sessions: {
    all: ['sessions'],
    list: (userId) => [...queryKeys.sessions.all, 'list', userId],
  },
  curriculum: {
    all: ['curriculum'],
    systems: () => [...queryKeys.curriculum.all, 'systems'],
    subjects: () => [...queryKeys.curriculum.all, 'subjects'],
    topics: (limit) => [...queryKeys.curriculum.all, 'topics', limit],
  },
  mrcp: {
    all: ['mrcp'],
    systems: (userId) => [...queryKeys.mrcp.all, 'systems', userId],
    topics: (userId) => [...queryKeys.mrcp.all, 'topics', userId],
  },
  localBoard: {
    all: ['localBoard'],
    cases: (userId) => [...queryKeys.localBoard.all, 'cases', userId],
  },
  uworld: {
    all: ['uworld'],
    blocks: (userId) => [...queryKeys.uworld.all, 'blocks', userId],
  },
  tracking: {
    all: ['tracking'],
    report: (userId) => [...queryKeys.tracking.all, 'report', userId],
    activity: (limit) => [...queryKeys.tracking.all, 'activity', limit],
    goals: () => [...queryKeys.tracking.all, 'goals'],
  },
  resources: {
    all: ['resources'],
    list: (category, type, search, sort) => [...queryKeys.resources.all, 'list', category, type, search, sort],
    detail: (id) => [...queryKeys.resources.all, 'detail', id],
    comments: (id) => [...queryKeys.resources.all, 'comments', id],
    pins: (userId) => [...queryKeys.resources.all, 'pins', userId],
  },
  categories: {
    all: ['categories'],
    list: () => [...queryKeys.categories.all, 'list'],
  },
  settings: {
    all: ['settings'],
    notifPrefs: () => [...queryKeys.settings.all, 'notifPrefs'],
    profile: (userId) => [...queryKeys.settings.all, 'profile', userId],
  },
  dashboard: {
    all: ['dashboard'],
    stats: (userId) => [...queryKeys.dashboard.all, 'stats', userId],
  },
  user: {
    all: ['user'],
    checkUsername: (username) => [...queryKeys.user.all, 'checkUsername', username],
  },
  forest: {
    all: ['forest'],
    sessions: (userId) => ['forest', 'sessions', userId],
  },
  research: {
    all: ['research'],
    list: (category, search, sort, status, communityId, page) => [...queryKeys.research.all, 'list', category, search, sort, status, communityId, page],
    detail: (id) => [...queryKeys.research.all, 'detail', id],
    comments: (id) => [...queryKeys.research.all, 'comments', id],
    helped: (id) => [...queryKeys.research.all, 'helped', id],
    bookmarks: () => [...queryKeys.research.all, 'bookmarks'],
    skills: (userId) => [...queryKeys.research.all, 'skills', userId],
    predefinedSkills: () => [...queryKeys.research.all, 'predefinedSkills'],
    stats: (userId) => [...queryKeys.research.all, 'stats', userId],
    events: (userId) => [...queryKeys.research.all, 'events', userId],
    profile: (userId) => [...queryKeys.research.all, 'profile', userId],
    portfolio: (userId) => [...queryKeys.research.all, 'portfolio', userId],
    leaderboard: (type, limit) => [...queryKeys.research.all, 'leaderboard', type, limit],
  },
  rotations: {
    all: ['rotations'],
    plans: () => [...queryKeys.rotations.all, 'plans'],
    plan: (id) => [...queryKeys.rotations.all, 'plan', id],
    schedule: (planId) => [...queryKeys.rotations.all, 'schedule', planId],
    progress: (planId) => [...queryKeys.rotations.all, 'progress', planId],
    flashcardSummary: () => [...queryKeys.rotations.all, 'flashcardSummary'],
    sources: () => [...queryKeys.rotations.all, 'sources'],
    sourceRotations: (sourceId) => [...queryKeys.rotations.all, 'sourceRotations', sourceId],
    sourceTopics: (sourceId, rotationId) => [...queryKeys.rotations.all, 'sourceTopics', sourceId, rotationId],
  },
}