name = "medstudy-web"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[triggers]]
  type = "cron"
  cron = "* * * * *"

[[d1_databases]]
binding = "DB"
database_name = "medstudy-db"
database_id = "6aee6015-9759-495a-8e3c-61e02e746c67"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "card-images"

[[durable_objects.bindings]]
  name = "COMMUNITY_REALTIME_ROOM"
  class_name = "CommunityRealtimeRoom"

[[durable_objects.bindings]]
  name = "DM_REALTIME_ROOM"
  class_name = "DMRealtimeRoom"

[[migrations]]
  tag = "v1"
  new_sqlite_classes = ["CommunityRealtimeRoom"]

[[migrations]]
  tag = "v2"
  new_sqlite_classes = ["DMRealtimeRoom"]

[vars]
SUPABASE_URL = "https://undakhccjrbcpzryfmot.supabase.co"
CF_ACCOUNT_ID = "a05b2fac1d43aa509d8765c8089f499b"
REALTIMEKIT_APP_ID = "96b410b8-1a27-477b-8fb9-eaa406775a82"
VAPID_PUBLIC_KEY = "BL1DR63woanpTniR80ObGZ3E2XeeSdmQoU1O8HKmVML6Lh40n58v05jg6cIkfCenkS8jkMyc81zX_fV-xdc1VHI"
